// Rectangular Waveguide
// Generated by VectorEM geometry generator
// a = 22.860 mm, b = 10.160 mm, L = 50.000 mm

lc = 0.002032;

// Cross-section at z=0
Point(1) = {0, 0, 0, lc};
Point(2) = {0.02286, 0, 0, lc};
Point(3) = {0.02286, 0.01016, 0, lc};
Point(4) = {0, 0.01016, 0, lc};

Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 1};

Curve Loop(1) = {1, 2, 3, 4};
Plane Surface(1) = {1};

// Extrude to create waveguide
Extrude {0, 0, 0.05} { Surface{1}; }

// Physical groups
Physical Surface("PEC", 1) = {13, 17, 21, 25};  // Walls
Physical Surface("Port1", 2) = {1};              // Input (z=0)
Physical Surface("Port2", 3) = {26};             // Output (z=L)
Physical Volume("Air", 100) = {1};

// Mesh settings
Mesh.Algorithm3D = 4;  // Frontal Delaunay
Mesh.Optimize = 1;
