import numpy as np
import matplotlib.pyplot as plt

# Load CSV generated by run_waveguide_demo.sh
data = np.loadtxt("examples/waveguide_sparams.csv", delimiter=",", skiprows=1)
freq = data[:, 0]
s11_mag = data[:, 1]
s21_mag = data[:, 2]

# Analytic expectation for straight, lossless waveguide
c0 = 299_792_458.0
A = 0.02286  # WR-90 width (m)
fc = c0 / (2.0 * A)
expected = np.where(freq > fc, 1.0, 0.0)

plt.plot(freq * 1e-9, s21_mag, label="VectorEM |S21|")
plt.plot(freq * 1e-9, expected, "--", label="Analytic |S21|")
plt.xlabel("Frequency (GHz)")
plt.ylabel("|S21|")
plt.legend()
plt.tight_layout()
plt.savefig("examples/waveguide_sparams.png", dpi=150)
