#!/usr/bin/env python3
"""
Mesh Convergence Study Automation

This script generates meshes at multiple density levels and runs
EdgeFEM simulations to produce convergence data for publication.

Usage:
    python run_convergence_study.py [--output-dir DIR]
"""

import subprocess
import sys
import os
import json
import argparse
from pathlib import Path

# Physical constants
c0 = 299792458.0
mu0 = 4.0 * 3.14159265358979323846 * 1e-7

# WR-90 parameters
a = 0.02286  # m
b = 0.01016  # m
L = 0.05    # m
freq = 10e9  # Hz

# Analytical values
omega = 2 * 3.14159265358979323846 * freq
k0 = omega / c0
kc = 3.14159265358979323846 / a
beta = (k0**2 - kc**2)**0.5
wavelength = c0 / freq

def generate_waveguide_mesh(mesh_size: float, output_path: str) -> bool:
    """Generate WR-90 waveguide mesh using Gmsh."""
    geo_content = f"""// WR-90 Waveguide - Convergence Study
// Generated by run_convergence_study.py

lc = {mesh_size};

// Waveguide dimensions in meters
a = {a};
b = {b};
L = {L};

// Cross-section at z=0
Point(1) = {{0, 0, 0, lc}};
Point(2) = {{a, 0, 0, lc}};
Point(3) = {{a, b, 0, lc}};
Point(4) = {{0, b, 0, lc}};

Line(1) = {{1, 2}};
Line(2) = {{2, 3}};
Line(3) = {{3, 4}};
Line(4) = {{4, 1}};

Curve Loop(1) = {{1, 2, 3, 4}};
Plane Surface(1) = {{1}};

// Extrude to create waveguide
Extrude {{0, 0, L}} {{ Surface{{1}}; }}

// Physical groups
Physical Surface("PEC", 1) = {{13, 17, 21, 25}};
Physical Surface("Port1", 2) = {{1}};
Physical Surface("Port2", 3) = {{26}};
Physical Volume("Air", 100) = {{1}};

Mesh.Algorithm3D = 4;
Mesh.Optimize = 1;
"""
    geo_path = output_path.replace('.msh', '.geo')
    with open(geo_path, 'w') as f:
        f.write(geo_content)

    result = subprocess.run(
        ['gmsh', '-3', '-format', 'msh2', '-o', output_path, geo_path],
        capture_output=True, text=True
    )

    if result.returncode != 0:
        print(f"Gmsh error: {result.stderr}")
        return False
    return True

def run_simulation(mesh_path: str, exe_path: str) -> dict:
    """Run EdgeFEM simulation and extract results."""
    # This would need the actual C++ executable
    # For now, return placeholder
    return None

def main():
    parser = argparse.ArgumentParser(description='Mesh Convergence Study')
    parser.add_argument('--output-dir', default='convergence_data',
                        help='Output directory for results')
    parser.add_argument('--build-dir', default='build',
                        help='EdgeFEM build directory')
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(exist_ok=True)

    # Mesh sizes: lambda/5, lambda/10, lambda/15, lambda/20, lambda/30
    mesh_sizes = [
        (5, wavelength / 5),
        (10, wavelength / 10),
        (15, wavelength / 15),
        (20, wavelength / 20),
        (30, wavelength / 30),
    ]

    print("=== Mesh Convergence Study ===")
    print(f"Wavelength: {wavelength * 1000:.2f} mm")
    print(f"Output directory: {output_dir}")
    print()

    results = []

    for lambda_per_h, h in mesh_sizes:
        print(f"Generating mesh with h = λ/{lambda_per_h} = {h*1000:.2f} mm...")
        mesh_name = f"wr90_h{lambda_per_h}.msh"
        mesh_path = str(output_dir / mesh_name)

        if generate_waveguide_mesh(h, mesh_path):
            print(f"  Mesh saved to {mesh_path}")

            # Count mesh statistics
            with open(mesh_path) as f:
                content = f.read()
                # Simple parsing to count nodes and elements
                if '$Nodes' in content:
                    nodes_section = content.split('$Nodes')[1].split('$EndNodes')[0]
                    n_nodes = int(nodes_section.strip().split('\n')[0])
                else:
                    n_nodes = 0

                if '$Elements' in content:
                    elements_section = content.split('$Elements')[1].split('$EndElements')[0]
                    n_elements = int(elements_section.strip().split('\n')[0])
                else:
                    n_elements = 0

            results.append({
                'lambda_per_h': lambda_per_h,
                'h_mm': h * 1000,
                'n_nodes': n_nodes,
                'n_elements': n_elements,
                'mesh_path': mesh_path,
            })
            print(f"  Nodes: {n_nodes}, Elements: {n_elements}")
        else:
            print(f"  Failed to generate mesh")
        print()

    # Save mesh statistics
    stats_path = output_dir / 'mesh_statistics.json'
    with open(stats_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"Mesh statistics saved to {stats_path}")

    # Print summary table
    print("\n=== Mesh Summary ===")
    print(f"{'λ/h':>6} {'h (mm)':>10} {'Nodes':>10} {'Elements':>10}")
    print("-" * 40)
    for r in results:
        print(f"{r['lambda_per_h']:>6} {r['h_mm']:>10.2f} {r['n_nodes']:>10} {r['n_elements']:>10}")

    print("\nTo run simulations, use the generated meshes with EdgeFEM.")
    print("Example:")
    print(f"  ./build/tests/test_mesh_convergence {output_dir}/wr90_h10.msh")

if __name__ == '__main__':
    main()
